### Create new item

POST http://0.0.0.0:5000/item HTTP/1.1
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI5ZTc5NWViLWRhMDMtNGQ5ZC05ZGEyLTg2ZTU3MjQ0MzI1NCIsInVzZXJuYW1lIjoidXNlcjEiLCJpc3N1ZWRfYXQiOiIyMDIxLTEwLTI0VDE0OjUxOjEyLjMwMjA0MDAyNyswMzowMCIsImV4cGlyZWRfYXQiOiIyMDIxLTEwLTI0VDE1OjUxOjEyLjMwMjA0MDIxNCswMzowMCJ9.pvGbtjZH5YiZUUm58eELYsw6Zf6RO5F0SPHAP3OucXI

{
    "name": "computer",
    "description": "test"
}

### Get item by id

GET http://0.0.0.0:5000/item?id=1 HTTP/1.1
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI5ZTc5NWViLWRhMDMtNGQ5ZC05ZGEyLTg2ZTU3MjQ0MzI1NCIsInVzZXJuYW1lIjoidXNlcjEiLCJpc3N1ZWRfYXQiOiIyMDIxLTEwLTI0VDE0OjUxOjEyLjMwMjA0MDAyNyswMzowMCIsImV4cGlyZWRfYXQiOiIyMDIxLTEwLTI0VDE1OjUxOjEyLjMwMjA0MDIxNCswMzowMCJ9.pvGbtjZH5YiZUUm58eELYsw6Zf6RO5F0SPHAP3OucXI