### Create user

POST http://0.0.0.0:5000/user HTTP/1.1
content-type: application/json

{
    "account": "manager",
    "password": "123",
    "role" : "user"
}

### Get user by id

GET http://0.0.0.0:5000/user?id=2 HTTP/1.1
content-type: application/json
token: 123